apiVersion: v1
kind: BuildConfig
metadata:
  name: sysbench-build
spec:
  source:
    git:
        uri: "git@gitlab.cee.redhat.com:css-sys/sysbench.git"
    type: Git
  strategy:
    dockerStrategy:
      noCache: true
  output:
    to:
      kind: ImageStreamTag
      name: sysbench:latest
